version: "3.5"

services:
  frontend-service:
    image: tp-frontend-service
    build: ./
    container_name: frontend-service

    ports:
      - "3000:3000"
    environment:
      - "URI_USER_SVC=http://192.168.1.146:8000"
