const URI_USER_SERVICE_HOSTNAME =
    process.env.URI_USER_SVC || "http://localhost:8000";
const URI_QUESTION_SERVICE_HOSTNAME =
    process.env.URI_QUESTION_SVC || "http://localhost:7000";

const PREFIX_USER_SVC = "/api/user";
const PREFIX_USER_SIGN_UP = "/api/user/signup";
const PREFIX_USER_LOGIN = "/api/user/login";
const PREFIX_USER_LOGOUT = "/api/user/logout";
const PREFIX_TOKEN_VALIDATION = "/api/user/validate-token";
const PREFIX_USER_DELETE = "/api/user/delete-user";
const PREFIX_USER_GET_USERNAME = "/api/user/get-username";
const PREFIX_USER_CHANGE_PASSWORD = "/api/user/change-password";

const PREFIX_CREATE_QUESTION = "/service/create/question";
const PREFIX_DELETE_QUESTION = "/service/delete/question";
const PREFIX_GET_RANDOM_QUESTION = "/service/get/random-id";
const PREFIX_GET_DIFFICULTY_LIMIT = "/service/get/limit";
const PREFIX_GET_QUESTION_ANSWER = "/service/get/question-answer";
const PREFIX_GET_ALL_QUESTIONS = "/service/get/all-questions";

export const URL_USER_SVC = URI_USER_SERVICE_HOSTNAME + PREFIX_USER_SVC;
export const URL_USER_LOGIN = URI_USER_SERVICE_HOSTNAME + PREFIX_USER_LOGIN;
export const URL_USER_SIGNUP = URI_USER_SERVICE_HOSTNAME + PREFIX_USER_SIGN_UP;
export const URL_USER_LOGOUT = URI_USER_SERVICE_HOSTNAME + PREFIX_USER_LOGOUT;
export const URL_TOKEN_VALIDATION =
    URI_USER_SERVICE_HOSTNAME + PREFIX_TOKEN_VALIDATION;
export const URL_USER_DELETE = URI_USER_SERVICE_HOSTNAME + PREFIX_USER_DELETE;
export const URL_USER_GET_USERNAME =
    URI_USER_SERVICE_HOSTNAME + PREFIX_USER_GET_USERNAME;
export const URL_USER_CHANGE_PASSWORD =
    URI_USER_SERVICE_HOSTNAME + PREFIX_USER_CHANGE_PASSWORD;

export const URL_CREATE_QUESTION =
    URI_QUESTION_SERVICE_HOSTNAME + PREFIX_CREATE_QUESTION;
export const URL_DELETE_QUESTION =
    URI_QUESTION_SERVICE_HOSTNAME + PREFIX_DELETE_QUESTION;
export const URL_GET_RANDOM_QUESTION =
    URI_QUESTION_SERVICE_HOSTNAME + PREFIX_GET_RANDOM_QUESTION;
export const URL_GET_DIFFICULTY_LIMIT =
    URI_QUESTION_SERVICE_HOSTNAME + PREFIX_GET_DIFFICULTY_LIMIT;
export const URL_GET_QUESTION_ANSWER =
    URI_QUESTION_SERVICE_HOSTNAME + PREFIX_GET_QUESTION_ANSWER;
export const URL_GET_ALL_QUESTIONS =
    URI_QUESTION_SERVICE_HOSTNAME + PREFIX_GET_ALL_QUESTIONS;
