export const STATUS_CODE_CREATED = 201
export const STATUS_CODE_DELETE_USER_SUCCESS = 202

export const STATUS_CODE_MISSING_PARAM = 400
export const STATUS_CODE_DELETE_USER_FAILED = 402
export const STATUS_CODE_CONFLICT = 409
export const STATUS_CODE_UNKNOWN_ERROR = 500

export const STATUS_CODE_LOGIN_SUCCESS = 200
export const STATUS_CODE_LOGIN_FAILED = 403
export const STATUS_CODE_LOGIN_MISSING = 400
