export const STATUS_CODE_CREATED = 201
export const STATUS_CODE_DELETE_USER_SUCCESS = 202

export const STATUS_CODE_MISSING_PARAM = 400
export const STATUS_CODE_INVALID_USER = 403
export const STATUS_CODE_CONFLICT = 409
export const STATUS_CODE_UNKNOWN_ERROR = 500

