export const STATUS_CODE_CREATED = 201
export const STATUS_CODE_CONFLICT = 409

export const STATUS_CODE_LOGIN_SUCCESS = 200
export const STATUS_CODE_LOGIN_FAILED = 403
export const STATUS_CODE_LOGIN_MISSING = 400
