name: Collaboration Service Deployment

on:
  workflow_dispatch:

  push:
    branches: [ "main" ]

defaults:
 run:
  working-directory: ./collaboration-service

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    env:
      ENV: TEST
      JWT_TEST_KEY: ${{ secrets.JWT_TEST_KEY }}
      DB_CLOUD_URI_TEST: ${{ secrets.DB_CLOUD_URI_TEST }}

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - run: npm install
    - run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create .env file  
        run: |
          echo "" > .env
          echo "DB_CLOUD_URI_PROD=${{ secrets.DB_CLOUD_URI_PROD }}" >> .env
          echo ENV="PROD" >> .env

      - name: Create ZIP deployment package
        run: zip -r collab-service.zip ./

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: "ap-southeast-1"

      - name: Upload package to S3 bucket
        run: aws s3 cp collab-service.zip s3://cs3219g49-tp-bucket/

      - name: Create new ElasticBeanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name "Collaboration Service" \
          --source-bundle S3Bucket="cs3219g49-tp-bucket",S3Key="collab-service.zip" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"

      - name: Deploy new ElasticBeanstalk Application Version
        run: aws elasticbeanstalk update-environment --environment-name cs3219g49-collab-service --version-label "ver-${{ github.sha }}"
