name: Frontend Deployment

on:
  workflow_dispatch:

  push:
    branches: [ "**" ]

defaults:
 run:
  working-directory: ./frontend

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm install --force  
    - run: npm run build

    - name: Create ZIP artifact
      run: zip -r build.zip ./build

    - uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: ./frontend/build.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: build-artifact

      - name: Unzip artifact
        run: unzip ./build.zip

      - name: Delete artifact
        run: rm ./build.zip

      - name: Create ZIP deployment package
        run: zip -r frontend.zip ./

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: "ap-southeast-1"

      - name: Upload package to S3 bucket
        run: aws s3 cp frontend.zip s3://cs3219g49-tp-bucket/

    