name: User Service Test

on:
  workflow_dispatch:

  push:
    branches: [ "**" ]

  pull_request:
    branches: [ "main" ]


defaults:
 run:
  working-directory: ./user-service

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      
      with:
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - run: npm ci
    - run: npm test
